### PR TITLE
Vol libs update

### PR DESCRIPTION
**Pull request by capnramses**
## Purpose of this PR

* To update the vol_libs libraries in Unreal. This latest version supports >2GB files, which may be required in Unreal plugin shortly for some studio/partner projects. Performance should also be slightly improved since the last version in Unreal.

## Changes made in this PR

* Copied in vol_libs files to the Source/Private/ directory.
* There is one API-breaking change from vol_libs (extra parameter to a function call), and that update is reflected in the unreal-specific volograms actor .cpp file here.

## Testing Summary

* Made a new 3D first-person game project and copied in the plugin - simulating a new user/download.
* Plugin compiled and loaded correctly.
* Tested with "gold-standard" Jan vologram.
* Tested with a 2GB hd studio capture and 2048x2048 video texture.
* All worked and performed well.

- [x] Explained how reviewers build, deploy, and test your code and what should they look for that would indicate a bug or regression.
- [x] Tested locally.
- [x] Named specific tools have you ran over the code: e.g. which { compilers, debuggers, fuzzers, profilers, sanitisers, linters, other tools }.
- [x] Explained inputs used to test for bugs. e.g. existing known working data, large files, empty files, etc.

## Risk Introduced and any Breaking Changes

I don't think any of the following apply. The vol_libs update is pretty well tested by now.

- [ ] This PR introduces breaking changes (API or ABI). Instructions are provided for existing users to update their projects.
- [ ] This PR introduces new dependencies. You have provided links and licences in this section. This is **_extremely important!_**.
- [ ] New dependencies: Explained how any new dependencies are linked and built againt - .dll, inline code etc.?
- [ ] Gaps in testing: Is any code not covered by tests?
- [ ] Gaps in testing: Are you unable to test on some platform? Or is some input data not available to you for testing?
- [ ] Analysed any other potential risks here.

## Pre-Merge Checklist

- [x] Before making your PR, refresh your branch with a merge from its parent in case of conflicting changes since you started your branch.
- [x] This PR description is written clearly so that reviewers can understand the why/what/how of the work done.
- [x] Reviewed your own PR and checked your changed code.
- [x] Invited a range of good reviewers.
- [x] Wait for a PR to be properly reviewed. Responded to all questions, and made any required changes.
- [x] Received one other reviewer's approval. Ideally wait for 2+ approvals, especially if you didn't get a thorough reivew on the first approval.
- [ ] If a reviewer asks a question, even if you have another approval, got the approval of the other reviewers as well before merging.
- [ ] Made sure existing reviewers approved any changes to the PR.
- [ ] Resolved any merge conflicts after making the PR.
- [ ] CI/CD builds are not reporting any errors.

### CODE REVIEW

**Comment by albemala** [comment]
is there another way of updating these deps, apart from copy files over?

**Comment by albemala** [comment]
do we support only one specific Unreal version, or do/did you test it against multiple version? is this specified somewhere in the repo (like do we say what Unreal version we support)?

**Review by valeria-volu — APPROVED** [review]

**Comment by capnramses** [comment]
> do we support only one specific Unreal version, or do/did you test it against multiple version? is this specified somewhere in the repo (like do we say what Unreal version we support)?

good question - and yes, just the one version. the Readme specifies it: `Built against Unreal version: 4.27`, but it's also specified in the main .uplugin file. When a new version is released I do my best update Unreal and test it. The big thing we have not yet considered supporting Unreal 5, although nobody has asked yet.

**Comment by capnramses** [comment]
> is there another way of updating these deps, apart from copy files over?

My experiences with git modules and subtrees on products has shown copying a couple of source files explicitly is by far the least painful way to update libraries in c/cpp projects! The trick is to make sure the libraries _can_ be just pulled in by copying source code - not requiring any tricky build scripts or anything.

We still need to compile & test locally anyway - especially in the case of API-breaking changes like this one, so the copy-paste doesn't take a large % of the time requirements.

The exception here is updates to dependencies of our libraries, like avcodec libraries. That's still kind of a pain, but I didn't need to do that in this case.

**Comment by albemala** [comment]
> > is there another way of updating these deps, apart from copy files over?
> 
> My experiences with git modules and subtrees on products has shown copying a couple of source files explicitly is by far the least painful way to update libraries in c/cpp projects! The trick is to make sure the libraries _can_ be just pulled in by copying source code - not requiring any tricky build scripts or anything.
> 
> We still need to compile & test locally anyway - especially in the case of API-breaking changes like this one, so the copy-paste doesn't take a large % of the time requirements.
> 
> The exception here is updates to dependencies of our libraries, like avcodec libraries. That's still kind of a pain, but I didn't need to do that in this case.

I know git modules and subtrees are a pain, I was thinking more of like compiling the dependency and importing it as a compiled lib. But I agree, if it's just a few files with no other dependencies or compile configs, then it's easier this way.

**Comment by capnramses** [comment]
clicked on the wrong button there...

**Pull request merged**
